### ISSUE TITLE
Optimalisatie WIK

### ISSUE THREAD

**Issue by d2hydro** [d2hydro/hydrodashboards#19]
From quote (NL):
[ ] Neerslagdata in WIK komt nu nog niet goed door. Ik kan niet tegelijk de drie type neerslagdata
inzien in de grafieken.
[ ] We meten op enkele plekken waterstanden in oppervlaktewater achter overstorten. Deze worden
eens per half uur getoond, die kan je niet combineren met data uit de keten.
[ ]  Kunnen we de rioolstelsels uit PDOK als kaartlaag meenemen in het WIK als WMS koppeling, of
wordt het WIK dan te traag?

**Comment by ngoorden** [comment]
- Neerslagdata van drie type neerslagdata komt nu goed door. 
- Waterstanden kunnen nu worden gecombineerd met data uit de keten.
- Gedaan!

**Comment by d2hydro** [comment]
Available in 0.5.2
