### ISSUE TITLE
Grafieken: Label waterhoogte en stijghoogte [m] moet [m NAP] worden: Prio -1

### ISSUE THREAD

**Issue by ngoorden** [d2hydro/hydrodashboards#72]

**Comment by d2hydro** [comment]
FEWS parameters request gives a usesDatum property per parameter. However, the datum itself cannot be found

See: https://www.hydrobase.nl/fews/nzv/FewsWebServices/rest/fewspiservice/v1/parameters

![Image](https://user-images.githubusercontent.com/43996424/200308755-c163751c-93a7-4951-b7d4-313e3aa1a2b3.png)

**Comment by d2hydro** [comment]
We added vertical_datum to the app config and the FEWS-API will return a parameterGroupName in a parameters request

**Comment by d2hydro** [comment]
fixed in 0.6.0
