### ISSUE TITLE
Grafieken: Label debiet_m3 [m3/s] moet debiet[m3/s] worden: Prio -1

### ISSUE THREAD

**Issue by ngoorden** [d2hydro/hydrodashboards#73]

**Comment by d2hydro** [comment]
FEWS parameters request: does not give the parametergroepname used in FEWS clients as label (together with the unit):

See: https://www.hydrobase.nl/fews/nzv/FewsWebServices/rest/fewspiservice/v1/parameters
![Image](https://user-images.githubusercontent.com/43996424/200308460-74b3e2b1-5d6b-43f7-9d14-247015e1e014.png)

**Comment by d2hydro** [comment]
fixed in 0.6.0
