### ISSUE TITLE
Peilbuis wordt in grafiek getoond als die geen data heeft. Ook geen data als er op historie knopje wordt gedrukt, zie voor selectie issue_85.py

### ISSUE THREAD

**Issue by ngoorden** [d2hydro/hydrodashboards#85]

**Comment by d2hydro** [comment]
relateert aan: https://github.com/d2hydro/hydrodashboards/issues/47. Wanneer timeseriessets zijn opgegeven in filters.xml, dan worden ook headers getoond van tijdseries die leeg zijn.
